name = "backend"
compatibility_date = "2023-12-01"

# [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDk3MGRmZGEtMzE2Mi00YTVhLTg2ZjYtOTJjNmZkMTZlOTM1IiwidGVuYW50X2lkIjoiOTYzOWQ3OGYyN2I1YzJjMTNmNmZhZDc2NjViNmJkMmRhYTRlYjkyMjRlMTk4YmEwMGM2NzFmNzcyM2FjYWE4ZCIsImludGVybmFsX3NlY3JldCI6Ijk1N2Y3MzNiLTc1NDEtNGFlNC04NmRmLTI3MjIyMzM0OTJjMyJ9.HXV9KeMUNSm9pnrWKAVay1MKaQxA-jj721DzVMmXkAw"

